### ISSUE TITLE
LSP lines displays diagnostic where they are not present.

### ISSUE THREAD

**Issue by B4mbus** [Maan2003/lsp_lines.nvim#10]
![image](https://user-images.githubusercontent.com/75364377/183131600-2fc8a84a-c226-414d-843e-e07592683081.png)
![image](https://user-images.githubusercontent.com/75364377/183131656-c6687569-f269-439c-8943-6710cc4d61d6.png)

It's visible in the screenshots. The lines' positions are wrong.
It's only present in some cases.

**Comment by Maan2003** [comment]
This is just mirror of https://git.sr.ht/~whynothugo/lsp_lines.nvim now. Please report issues there.
