### ISSUE TITLE
Lines keep to be long

### ISSUE THREAD

**Issue by anton-nikan** [Maan2003/lsp_lines.nvim#5]
For some reason I keep getting very long lines from lsp_line:
![Screenshot from 2022-06-27 22-50-54](https://user-images.githubusercontent.com/593183/176025255-37d41811-e93f-40b1-80ff-bc29e23de2ea.png)

Using the same config as in Readme.
From the code it seems the text is assumed to come already pre-split from the language server, is it so?

**Comment by Maan2003** [comment]
We just split on line breaks. I don't want to manually implement wrapping

**Comment by anton-nikan** [comment]
Yeah, it seems like clangd doesn't split that much. I'll try finding if there's any way to force it there.

**Comment by omerdn1** [comment]
@Maan2003 In the example anton sent, the issue isn't that the library didn't implement line breaks correctly. It's that line 31 is long enough that almost any text will go out of screen when in split view.

I've been using lsp_lines for the past couple of weeks and I can tell the issue of lines going out of screen is fairly common, especially when using my laptop screen, and even more so when using split views.
I would highly advocate for adding a wrapping option that's aware of the window's borders.

**Comment by Maan2003** [comment]
This is just mirror of https://git.sr.ht/~whynothugo/lsp_lines.nvim now. Please report issues there.
