### ISSUE TITLE
Upstream

### ISSUE THREAD

**Issue by WhyNotHugo** [Maan2003/lsp_lines.nvim#6]
Hey! I found your fork (it's actually further up in results than mine :joy: ) and really like the improvements you've made.

I've picked up the changes and merged them in -- it was tricky due to a lot of conflicts due to divergence, but I attempted to keep authorship.

I fixed a bug that's apparently not an issue with your theme: whitespace around the ascii arrows also has the diagnostics highlight applied, and will have the background applied:

![2022-07-22T14:34:50,092816851+02:00](https://user-images.githubusercontent.com/730811/180486359-d83073f8-3610-4f0a-80a4-6d25ee498cee.png)

I also added a `├` in bits where it makes sense:

![2022-07-22T18:48:57,711755550+02:00](https://user-images.githubusercontent.com/730811/180486621-c75bcdcf-042a-4c80-80b9-512641076dd6.png)

That last part was tricky, and required re-thinking the whole algorithm. But it was a bunch of fun!

Thanks for improving lsp_lines! Enjoy!

(feel free to close this)

**Comment by Maan2003** [comment]
Wow, you are awesome! My changes were very hacky, thanks for merging.

Do you know how to suggest users using my fork to migrate?

**Comment by WhyNotHugo** [comment]
> Wow, you are awesome! My changes were very hacky, thanks for merging.

They were a good referrence to understand exactly what I wanted thing to look like.

> Do you know how to suggest users using my fork to migrate?

That's up to you. I don't think it's easy to merge in the changes, since I didn't do a merge commit. I wanted to avoid merging the screenshots due to size. In hindsight, I that would have made pulling easier, plus, now the screenshot is outdated :joy: . You can fetch/reset-hard/force-push if you want; the won't have to update their remotes.

**Comment by Maan2003** [comment]
(force pushed)
