### ISSUE TITLE
[Feature request] Open diagnostics in float

### ISSUE THREAD

**Issue by timoleistner** [Maan2003/lsp_lines.nvim#9]
Hey cool plugin, I really like the tree-like diagnostics view.
Would be cool to be able to optionally open diagnostics in a floating window instead of shifting everything below.
Just like `vim.diagnostic.open_float()` but with your tree-like indications :)

**Comment by Maan2003** [comment]
This is just a mirror, report issues at https://todo.sr.ht/~whynothugo/lsp_lines.nvim
